package com.esec.examprep.presentation.share

import android.content.Context
import android.content.Intent
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import com.esec.examprep.domain.model.ExamResult
import com.esec.examprep.domain.model.Grade
import com.esec.examprep.domain.model.UserProgress
import com.esec.examprep.domain.model.WeakTopic
import java.io.File
import java.io.FileOutputStream
import java.time.ZoneId
import java.time.format.DateTimeFormatter

object PdfExporter {

    private const val PAGE_W = 595
    private const val PAGE_H = 842
    private val DATE_FMT: DateTimeFormatter =
        DateTimeFormatter.ofPattern("MMM d, yyyy").withZone(ZoneId.systemDefault())

    fun exportProgressPdf(
        context: Context,
        profileName: String?,
        progress: List<UserProgress>,
        recent: List<ExamResult>,
        weakTopics: List<WeakTopic>,
        avgTimePerQuestion: Double,
    ) {
        val doc = PdfDocument()
        val page = doc.startPage(PdfDocument.PageInfo.Builder(PAGE_W, PAGE_H, 1).create())
        val canvas = page.canvas

        val title = Paint().apply {
            color = Color.BLACK; textSize = 22f; isAntiAlias = true
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }
        val h2 = Paint(title).apply { textSize = 14f }
        val body = Paint().apply { color = Color.DKGRAY; textSize = 11f; isAntiAlias = true }
        val muted = Paint(body).apply { color = Color.GRAY; textSize = 10f }
        val rule = Paint().apply { color = Color.LTGRAY; strokeWidth = 1f }

        var y = 50f
        canvas.drawText("ESEC Progress Report", 40f, y, title)
        y += 22f
        canvas.drawText(profileName ?: "All progress", 40f, y, muted)
        y += 22f
        canvas.drawLine(40f, y, (PAGE_W - 40).toFloat(), y, rule)
        y += 20f

        val totalExams = progress.sumOf { it.totalAttempts }
        val overallGpa = Grade.weightedGpa(
            progress.map { it.averageScore to it.totalAttempts },
        )
        canvas.drawText("Overview", 40f, y, h2); y += 16f
        canvas.drawText("Total exams: $totalExams", 40f, y, body); y += 14f
        canvas.drawText("Overall GPA: ${"%.2f".format(overallGpa)}", 40f, y, body); y += 14f
        canvas.drawText("Avg time per question: ${"%.1f".format(avgTimePerQuestion)} s", 40f, y, body); y += 22f

        if (progress.isNotEmpty()) {
            canvas.drawText("Subjects", 40f, y, h2); y += 16f
            progress.take(20).forEach { p ->
                val grade = Grade.fromPercent(p.averageScore)
                val line = "• ${p.subjectName}  —  ${"%.1f".format(p.averageScore)}%  " +
                    "(${grade.letter}, GPA ${"%.2f".format(grade.gpa)}, ${p.totalAttempts} exams)"
                canvas.drawText(line, 40f, y, body); y += 14f
                if (y > PAGE_H - 80) return@forEach
            }
            y += 8f
        }

        if (weakTopics.isNotEmpty() && y < PAGE_H - 120) {
            canvas.drawText("Weak topics", 40f, y, h2); y += 16f
            val nameById = progress.associate { it.subjectId to it.subjectName }
            weakTopics.take(8).forEach { w ->
                val name = nameById[w.subjectId] ?: w.subjectId
                val line = "• $name  —  ${"%.0f".format(w.errorRate * 100)}% error over ${w.attempts} attempts"
                canvas.drawText(line, 40f, y, body); y += 14f
                if (y > PAGE_H - 80) return@forEach
            }
            y += 8f
        }

        if (recent.isNotEmpty() && y < PAGE_H - 120) {
            canvas.drawText("Recent exams", 40f, y, h2); y += 16f
            recent.take(8).forEach { r ->
                val date = DATE_FMT.format(r.completedAt)
                val grade = Grade.fromPercent(r.scorePercent)
                val line = "• $date  —  ${r.subjectName}  ${"%.0f".format(r.scorePercent)}% (${grade.letter})"
                canvas.drawText(line, 40f, y, body); y += 14f
                if (y > PAGE_H - 60) return@forEach
            }
        }

        canvas.drawText("Generated by ESEC", 40f, (PAGE_H - 30).toFloat(), muted)

        doc.finishPage(page)

        val dir = File(context.cacheDir, "shared").apply { mkdirs() }
        val file = File(dir, "esec_progress_${System.currentTimeMillis()}.pdf")
        FileOutputStream(file).use { doc.writeTo(it) }
        doc.close()

        val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
        val send = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_SUBJECT, "ESEC Progress Report")
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(send, "Share progress PDF").apply {
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        })
    }
}
